// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartDocs.Models;

namespace SmartDocs.Migrations
{
    [DbContext(typeof(SmartDocContext))]
    [Migration("20181019020119_AddDocNameToSmartPPA")]
    partial class AddDocNameToSmartPPA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartPPA.Models.SmartJob", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobData")
                        .HasColumnType("xml");

                    b.Property<string>("JobName");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SmartPPA.Models.SmartPPA", b =>
                {
                    b.Property<int>("PPAId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("DocumentName");

                    b.Property<string>("FormData")
                        .HasColumnType("xml");

                    b.Property<int?>("JobId");

                    b.Property<DateTime>("Modified");

                    b.Property<int?>("OwnerUserId");

                    b.Property<int?>("TemplateId");

                    b.HasKey("PPAId");

                    b.HasIndex("JobId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PPAs");
                });

            modelBuilder.Entity("SmartPPA.Models.SmartTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("DataStream");

                    b.Property<string>("DocumentName");

                    b.HasKey("TemplateId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("SmartPPA.Models.SmartUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlueDeckId");

                    b.Property<string>("DisplayName");

                    b.Property<string>("LogonName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartPPA.Models.SmartPPA", b =>
                {
                    b.HasOne("SmartPPA.Models.SmartJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("SmartPPA.Models.SmartUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.HasOne("SmartPPA.Models.SmartTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");
                });
#pragma warning restore 612, 618
        }
    }
}
